### ISSUE TITLE
подготовить схему данных голосов в БД и миграции

### ISSUE THREAD

**Issue by vitalyshatskikh** [larikhide/barradio#7]
Создать в БД таблицы для хранения данных голосования (с учетом #4, #5, #6)

Подготовить скрипты миграции

**Comment by sanya-spb** [comment]
пока вижу такую структуру, если по классике, то с нормализацией:

| Users | список зарегистрированных юзеров
- id
- uuid
- nickname
- device_id (надо ли идентифицировать юзера по девайсу?)
- ... ну пароль, номер телефона и т.д. и т.п. в зависимости от того что во фронте при регистрации требуется

| genres | Жанры/настроения/стили
- id
- genre
- descr
- [ ] нужно ли тут дерево (поджанры, подстили)?


| voteuuids | как назвать рабочую табличку, с голосами?
- id
- id_user
- id_genre
- timestamp
...


либо по тенденции: сразу в json, без нормализации... либо хранить по классике, а выдавать можно и json-ом
надо обсудить..

**Comment by vitalyshatskikh** [comment]
в Users id и uuid дубрируют друг друга, в остальном согласен.
дерево поджанров, думаю, можно пока не делать

**Comment by larikhide** [comment]
> в Users id и uuid дубрируют друг друга, в остальном согласен. дерево поджанров, думаю, можно пока не делать

поддерживаю по id, думаю, что можно оставить только uuid. Дерево поджанров сделаем потом, если останется время как фичу

**Comment by vitalyshatskikh** [comment]
Реализовано pr #25
